// Cove API type surface.
//
// This module re-exports the API contract types from the generated @cove/types package
// (derived from the committed OpenAPI document) plus a small set of client-only convenience
// shapes. The public names below are preserved verbatim so existing "../api/types" imports
// keep resolving unchanged. There are no hand-written DTO definitions here: the single source
// of truth for every shape is @cove/types.

// Types whose generated name matches the public name used across the UI.
export type {
  AffinityHostType,
  AiDataKind,
  AiDataPurgeRequest,
  AiDataPurgeResult,
  AiDataSelector,
  AiDataSummary,
  AiDataSummaryItem,
  AiFaceCoverRepairRequest,
  AiFaceCoverRepairResult,
  ApplyScrapeAttemptRequest,
  Audio,
  AudioCreate,
  AudioFile,
  AudioSimilarVideo,
  AudioUpdate,
  AuthUserKind,
  BookmarkBatchRequest,
  BookmarkState,
  BookmarkToggle,
  BoolCriterion,
  BulkAudioUpdate,
  BulkGalleryUpdate,
  BulkGroupUpdate,
  BulkImageUpdate,
  BulkPerformerUpdate,
  BulkStudioUpdate,
  BulkTagUpdate,
  BulkUpdateMode,
  BulkVideoUpdate,
  Caption,
  CoveConfig,
  CriterionModifier,
  CustomFieldDefinitionCreate,
  CustomFieldDefinitionUpdate,
  CustomFieldEntityType,
  CustomFieldType,
  DatabaseMigrationResult,
  DateCriterion,
  DeleteEntityOptions,
  DependencyInfo,
  DependencyProblem,
  Detection,
  DetectionCreate,
  DetectionHostType,
  DetectionUpdate,
  DownloaderBatchFollowUp,
  DownloaderBatchGenerateOptions,
  DownloaderBatchIssue,
  DownloaderBatchStartRequest,
  DownloaderBatchStartResponse,
  DownloaderDescriptor,
  DownloaderMatch,
  DownloaderMatchRequest,
  DownloaderPreflightRequest,
  DownloaderPreflightResponse,
  DownloaderQualityOption,
  DynamicGroupSource,
  EntityEngagement,
  EntityEngagementBatchRequest,
  EntityFavorite,
  EntityRatings,
  ExtensionAction,
  ExtensionDependencyImpact,
  ExtensionExternalDependency,
  ExtensionInfo,
  ExtensionSettingManifest,
  Face,
  FaceAppearance,
  FaceAppearancesResponse,
  FaceBatchFailed,
  FaceBatchOperationResult,
  FaceBatchSkipped,
  FaceCreate,
  FaceCreatePerformer,
  FaceDeleteImpact,
  FaceHostFace,
  FaceIgnore,
  FaceLink,
  FaceMerge,
  FaceNotPresentResult,
  FaceSimilar,
  FaceSuggestion,
  FaceSuggestionEvidence,
  FaceTopSuggestion,
  FaceUpdate,
  FfmpegCapabilities,
  FieldProvenance,
  FileBackedCreate,
  FilteredQueryRequest,
  FindFilter,
  Fingerprint,
  FingerprintAlgorithm,
  FingerprintCriterion,
  Gallery,
  GalleryChapter,
  GalleryChapterCreate,
  GalleryChapterUpdate,
  GalleryCreate,
  GalleryFileInfo,
  GallerySummary,
  GalleryUpdate,
  Group,
  GroupCreate,
  GroupItem,
  GroupItemCreate,
  GroupItemKind,
  GroupItemsFromSpans,
  GroupItemSpanInput,
  GroupItemsRemoveHosts,
  GroupItemsReorder,
  GroupItemUpdate,
  GroupKind,
  GroupPlaybackManifest,
  GroupPlaybackManifestItem,
  GroupQueryUpdate,
  GroupSummary,
  GroupUpdate,
  IdentifyDefaultsConfig,
  Image,
  ImageCreate,
  ImageFile,
  ImageUpdate,
  IntCriterion,
  InteractionHostType,
  InterfaceConfig,
  JobInfo,
  MeResponse,
  MetadataBatchDefaultsConfig,
  MetadataServer,
  MetadataServerEntityCandidate,
  MetadataServerFindByIdsRequest,
  MetadataServerFingerprint,
  MetadataServerPerformerBatchTagRequest,
  MetadataServerPerformerImportRequest,
  MetadataServerPerformerMatch,
  MetadataServerStudioBatchTagRequest,
  MetadataServerStudioImportRequest,
  MetadataServerStudioMatch,
  MetadataServerTagBatchTagRequest,
  MetadataServerTagImportRequest,
  MetadataServerTagMatch,
  MetadataServerValidationResult,
  MetadataServerVideoEntityOverride,
  MetadataServerVideoImportRequest,
  MetadataServerVideoMatch,
  MultiIdCriterion,
  PaginatedResponse,
  Performer,
  PerformerCreate,
  PerformerRemoteId,
  PerformerScrapePreview,
  PerformerScrapeRequest,
  PerformerSummary,
  PerformerUpdate,
  PlaybackInterval,
  PlaybackIntervalInput,
  PlaybackIntervalsRequest,
  Plugin,
  PluginSettings,
  PluginSettingSchema,
  PluginTask,
  RatingStarPrecision,
  RatingSystemOptions,
  RatingSystemType,
  RegistryExtensionDetail,
  RegistryExtensionSummary,
  RegistryInstallResult,
  RegistrySearchResult,
  RegistryUninstallResult,
  RegistryUpdateInfo,
  RegistryVersionInfo,
  ResolvedSpan,
  ResolvedSpanDetail,
  ResolvedSpanInterval,
  ResolvedSpanList,
  ResolveScrapeRelationsRequest,
  ResolveScrapeRelationsResult,
  SavedFilter,
  SavedFilterCreate,
  SavedFilterUpdate,
  ScrapeApplyDefaultsConfig,
  ScrapeAttempt,
  ScrapeCollectionItemAction,
  ScrapeCollectionItemSelection,
  ScrapedPerformer,
  ScrapeRelationMatch,
  ScraperPreference,
  ScraperSummary,
  ScrapingConfig,
  SecurityConfig,
  SegmentCreate,
  SegmentDerivedQueryDescriptor,
  SegmentDerivedQueryOperandDescriptor,
  SegmentDisplayProfile,
  SegmentDisplayProfileCreate,
  SegmentDisplayProfilePreviewRequest,
  SegmentDisplayProfileUpdate,
  SegmentDisplayRule,
  SegmentDisplayRuleCreate,
  SegmentDisplayRuleUpdate,
  SegmentDistinctValue,
  SegmentHostType,
  SegmentRecord,
  SegmentSpanCountResponse,
  SegmentSpanDerivedQuery,
  SegmentSpanOperand,
  SegmentSpanOperator,
  SegmentSpanQueryRequest,
  SegmentSpanSearchRequest,
  SegmentSpanSearchResponse,
  SegmentSpanSearchResultItem,
  SegmentUpdate,
  Stats,
  StringCriterion,
  Studio,
  StudioCreate,
  StudioRemoteId,
  StudioUpdate,
  SystemStatus,
  TagApplication,
  TagApplicationCreate,
  TagCreate,
  TagDetail,
  TagDurationClause,
  TagDurationCriterion,
  TagGraphLink,
  TagGraphNode,
  TagGraphResponse,
  TagGroup,
  TagGroupCreate,
  TagGroupUpdate,
  TagProvenance,
  TagRemoteId,
  TagSegmentWall,
  TagUpdate,
  TextContent,
  TextDocument,
  TextFile,
  TimestampCriterion,
  UiConfig,
  UserPlaybackPreferences,
  UserThemePreferences,
  UserTrackingPreferences,
  UserUiPreferences,
  UserVideosPreferences,
  Video,
  VideoCreate,
  VideoFile,
  VideoFilterCriteria,
  VideoGroupInput,
  VideoHistory,
  VideoListEntry,
  VideoPlaybackSession,
  VideoRemoteId,
  VideoResolvedSpans,
  VideoUpdate,
  VisualSimilarImage,
  VisualSimilarVideo,
} from "@cove/types";

// Types the generator emits under a different name (schema-id / naming reconciliation).
export type {
  ApplyVideoScrapeAttempt as ApplyVideoScrapeAttemptRequest,
  AudioFilter as AudioFilterCriteria,
  AudioTrack as AudioTrackInfo,
  Bookmark as BookmarkDto,
  BulkTextDocumentUpdate as BulkTextUpdate,
  CovePath as CovePathConfig,
  CreateScrapeAttempt as CreateScrapeAttemptRequest,
  DownloaderPathOverride as DownloaderPathOverrideConfig,
  UiComponentStyleDef as ExtensionComponentStyleDef,
  UiDialogOverride as ExtensionDialogOverride,
  UiFeatureDefinition as ExtensionFeatureDef,
  UiLayoutStyleDef as ExtensionLayoutStyleDef,
  UiListFilterContribution as ExtensionListFilterContribution,
  UiListFilterOption as ExtensionListFilterOption,
  UiListSortContribution as ExtensionListSortContribution,
  UiManifest as ExtensionManifest,
  UiPageDefinition as ExtensionPageDef,
  UiPageOverride as ExtensionPageOverride,
  UiSettingsPanel as ExtensionSettingsPanel,
  UiSettingsTab as ExtensionSettingsTab,
  UiSlotContribution as ExtensionSlotContribution,
  UiTabContribution as ExtensionTabContribution,
  UiThemeDefinition as ExtensionThemeDef,
  UiTutorialLink as ExtensionTutorialLink,
  UiTutorialSlide as ExtensionTutorialSlide,
  UiTutorialTopic as ExtensionTutorialTopic,
  FaceBatchDelete as FaceBatchDeleteRequest,
  FaceBatchLinkTopSuggestion as FaceBatchLinkTopSuggestionRequest,
  GalleryFilter as GalleryFilterCriteria,
  GroupFilter as GroupFilterCriteria,
  GroupItemsReorder as GroupReorder,
  ImageFilter as ImageFilterCriteria,
  PerformerFilter as PerformerFilterCriteria,
  RunPluginTask as RunPluginTaskRequest,
  StudioFilter as StudioFilterCriteria,
  TagFilter as TagFilterCriteria,
  TextDocumentCreate as TextCreate,
  TextDocumentFilter as TextFilterCriteria,
  TextDocumentUpdate as TextUpdate,
  InteractionEvent as VideoInteractionEvent,
} from "@cove/types";

// Client views that add UI-held fields on top of a wire type of the same public name.
export type {
  CustomFieldCriterionView as CustomFieldCriterion,
  CustomFieldDefinitionView as CustomFieldDefinition,
  DownloaderBatchItemView as DownloaderBatchItem,
  DownloaderStartRequestView as DownloaderStartRequest,
  EngagementInteractionView as EngagementInteraction,
  EngagementInteractionWriteView as EngagementInteractionWrite,
  SegmentView as Segment,
  TagView as Tag,
} from "@cove/types";
